#!/bin/sh
# Spawn a new java process with our Executor
exec java -cp /vagrant/framework-1.0.jar:/vagrant/protobuf-java-2.5.0.jar:/usr/share/java/mesos-0.28.1.jar \
  com.andresolarte.mesos.framework.TestExecutor "${@}"
